export type ComponentKeys =
	| "aero-numeric-input"
	| "aero-spinbox"
	| "aero-progress-spinner"
	| "aero-progress-indeterminate-spinner"
	| "aero-resizable-box"
	| "aero-select"
	| "aero-option"
	| "aero-toast"
	| "aero-popup"
